### PR TITLE
Select contract command

### PR DESCRIPTION
**Pull request by RSJunior37**

### CODE REVIEW

**Comment by OscarWang114** [comment]
@Juxarius  I need your help resolving this merge conflict.

**Comment by OscarWang114** [comment]
Failed to pass Travis after resolving conflict due to multiple functions having the same name and signature. @RSJunior37  @Juxarius  I need you guys to decide whose implementation are we keeping and discard the other.

**Comment by Juxarius** [comment]
i would suggest keeping mine given a more flexible implementation.
I extended the select command to allow it to choose insurance, person is by default
@RSJunior37 made a new command for it instead
objectively, i would say my implementation is better

EDIT: checked the issues, i did raise it earlier, so i believe i did say i was doing this feature

**Comment by RSJunior37** [comment]
Yes I realize the duplicate, but I believe you were the one who told me to do the tab textfield feature **and** this select insurance on last Thursday, so I am as perplexed as you to how did we end up in this situation. That aside, I'll be closing this PR

**Comment by Juxarius** [comment]
Yep ps my bad cos i said that then i forgot then when i checked the issues i just thought of it so i went ahead

**Pull request closed without merging**
