### PR TITLE
Update my collate md files and add a few tests

### PR DESCRIPTION
**Pull request by Pujitha97**

### CODE REVIEW

**Comment by arnollim** [comment]
Hey Pujitha, how long has Travis been running on your PR? The yellow dot seems to have been there for a while

**Comment by Pujitha97** [comment]
@arnollim Im not sure why the yellow dot is still there. Good question. Because the build has actually passed as shown in travis. Im gonna try and restart the build.

**Comment by Pujitha97** [comment]
Restarting the builds has helped! Checks have passed.

**Review by OscarWang114 — APPROVED** [review]
Approved

**Pull request merged**
